CREATE DATABASE customer_behaviour;
USE customer_behaviour;

ALTER USER 'root'@'localhost' IDENTIFIED BY 'NewPassword123';
FLUSH PRIVILEGES;

SHOW TABLES;
 SELECT * FROM customer_shopping;

-- What is the total revenue generated by male vs female customer?
SELECT gender, SUM(purchase_amount) AS total_revenue
FROM customer_shopping
GROUP BY gender
;

-- Which customers used discount but still spent more than the average purchase amount

SELECT customer_id, purchase_amount
FROM customer_shopping
WHERE discount_applied = 'Yes' AND 
purchase_amount > (SELECT AVG(purchase_amount) FROM customer_shopping)
;

-- Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating), 2) AS Average_Review_Rating
FROM customer_shopping
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5
;

-- Compare the Average purchase amount between the Standard and Express Shipping
SELECT AVG(purchase_amount) AS Average_Purchase_Amount, shipping_type
FROM customer_shopping
WHERE shipping_type IN ('Express' , 'Standard')
GROUP BY shipping_type
;

-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers
SELECT COUNT(customer_id), subscription_status, AVG(purchase_amount) AS Avg_Purchase_Amount, 
SUM(purchase_amount) AS Total_Revenue
FROM customer_shopping
GROUP BY subscription_status
;

-- Which 5 products have the highest precentage of purchases with discounts applied?
SELECT item_purchased, 
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0/COUNT(*), 2) AS discount_purchases
FROM customer_shopping
GROUP BY item_purchased
ORDER BY discount_purchases DESC
LIMIT 5
;

-- Segment customers into New, Returning, Loyal based on their total number of previous purchases and show the count of each segment
WITH CTE AS(
SELECT customer_id, previous_purchases, 
CASE WHEN previous_purchases = 1 THEN 'New'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
WHEN previous_purchases >= 10 THEN 'Loyal' END AS customer_segment
FROM customer_shopping)

SELECT customer_segment, COUNT(*) AS numb_customer
FROM CTE
GROUP BY customer_segment
;

-- What are the top 3 most purchased products within each category
WITH CTE AS(
SELECT item_purchased, category, purchase_amount, COUNT(customer_id) AS total_orders, 
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer_shopping
GROUP BY item_purchased, category)
SELECT item_rank, item_purchased, category, total_orders
FROM CTE
WHERE item_rank <= 3
;

-- What is the revenue contribution of each age group
SELECT age_group, SUM(purchase_amount) AS revenue_contri
FROM customer_shopping
GROUP BY age_group
ORDER BY revenue_contri DESC
;

-- Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
SELECT  subscription_status, COUNT(customer_id) AS count_id
FROM customer_shopping
WHERE previous_purchases > 5
GROUP BY subscription_status
;
